### ISSUE TITLE
Cannot read property 'substr' of undefined 

### ISSUE THREAD

**Issue by oinkbark** [madhusudanbabar/k-domains#10]
Version:
1.2.5

Config:
```js
buildModules: [
    [ 'k-domains', { subDomains: [ 'api' ], rootDomain: 'root' } ],
    [ '@nuxtjs/router', { keepDefaultRouter: true } ]
  ]
```

Layout:
```
/pages
  /api
    index.vue
    api.pug
    api.styl
    api.ts
  /root
    index.vue
    /login
      index.vue
      login.pug
      login.styl
      login.ts
    /index
      index.pug
      index.styl
      index.ts
```

Error:
```
 ERROR  Cannot read property 'substr' of undefined 

  at server.js:1965:28
  at Array.map (<anonymous>)
  at createRouter (src/router.js:57:0)
  at router_createRouter (src/.nuxt/router.js:6:0)
  at createApp (src/.nuxt/index.js:69:0)
  at module.exports.__webpack_exports__.default (src/.nuxt/server.js:82:0)
  at node_modules/vue-server-renderer/build.prod.js:1:78608
  at new Promise (<anonymous>)
  at node_modules/vue-server-renderer/build.prod.js:1:78080
  at Object.renderToString (node_modules/vue-server-renderer/build.prod.js:1:81615)
  ```
  
  I attached a console.log to route.path and route.name (line 57 on router.js) and this is what the output was:
  ```
/api
api
/api/api
api-api
/root
undefined
/root/login
root-login
/root/login/login
root-login-login
  ```
  
  Possible Solution:
 (I made this change manually to my setup and it made it work)
change this:
```
return {
  ...route,
  path: route.path.substr(routesDirectory.length + 1) || "/",
  name: route.name.substr(routesDirectory.length + 1) || "index"
}
```
to this: (add optional chaining)
```
return {
  ...route,
  path: route.path?.substr(routesDirectory.length + 1) || "/",
  name: route.name?.substr(routesDirectory.length + 1) || "index"
}
```

**Comment by madhusudanbabar** [comment]
Hey, thanks for pointing out that, I'll surely push an update.
